# ==========================================================
# Wireless Downlink Optimization under Sparse Jamming Attacks
# Windows Local Version
# Modified to load data from .mat files generated by data-wireless-mat.jl
# ==========================================================

using JuMP, MosekTools, CSV, DataFrames, Distributions, LinearAlgebra, Printf, Random
using PrettyTables, Combinatorics, Statistics
using MAT  # Added for loading .mat files

# --- 1. Load Data from .mat File ---
function load_wireless_data(n_BS, n_J, m_UE; seed=42, mat_dir="instances")
    fname = joinpath(mat_dir, "RJ_$(n_BS)BS_$(n_J)J_$(m_UE)UE_seed$(seed).mat")
    if !isfile(fname)
        error("MAT file not found: $fname. Please generate it using data-wireless-mat.jl.")
    end
    data = matread(fname)
    
    h =  data["gains_h"]  # m_UE x n_BS
    g_mat =  data["gains_g"]  # m_UE x n_BS x n_J
    g = permutedims(g_mat, [1, 3, 2])  # Permute to m_UE x n_J x n_BS to match algorithm's g[k, j, i]
    
    p_bar = ones(n_BS) * data["p_max"] #* 1.5  # Increase by 50% # Use p_max from .mat (e.g., 40.0)
    gamma = fill(data["gamma"], m_UE)  # Vector of gamma values
    sigma2 = data["noise"]  # Noise vector from .mat
    # 🔑 CRITICAL: Load U_max and u_max from .mat (no hardcoding!)
    U_max = data["Umax"]
    u_max = data["umax"]
    return h, g, p_bar, gamma, sigma2, U_max, u_max
end

# --- 2. Sparse Projection onto {0 ≤ u ≤ 1, ‖u‖₀ ≤ s} ---
function sparse_project(u_tilde, s)
    n = length(u_tilde)
    idx = sortperm(abs.(u_tilde), rev=true)[1:s]
    u_proj = zeros(n)
    for i in idx
        u_proj[i] = max(u_tilde[i], 0)  # Ensure non-negativity
    end
    return u_proj
end

# --- 3. Worst-Case Subproblem for User k ---
function worst_case_jammer(c_k, s; method="heuristic", optimizer=Mosek.Optimizer, total_time=0.0,
                           U_max=1000.0,   # ← added
                           u_max=800.0)    # ← added
    n_J = length(c_k)
    #Umax=1000
    #umax=800
    model = Model(optimizer)
    set_silent(model)
    remaining_time = max(0.0, 1000.0 - total_time)
    set_optimizer_attribute(model, "MSK_DPAR_OPTIMIZER_MAX_TIME", remaining_time)

    if method == "heuristic"
        @variable(model, 0 <= u[1:n_J]<=u_max)
        @constraint(model, sum(u[j]^2 for j in 1:n_J) <= U_max^2)
        @objective(model, Max, sum(c_k[j] * u[j] for j in 1:n_J))
        optimize!(model)
        if termination_status(model) != MOI.OPTIMAL
            @warn "Heuristic subproblem not optimal: $(termination_status(model)), time used: $(solve_time(model))s"
            return zeros(n_J)
        end
        u = value.(u)
        return sparse_project(u, s)
    elseif method == "mip"
        @variable(model, 0 <= u[1:n_J] <=u_max)
        @variable(model, z[1:n_J], Bin)
        @constraint(model, u .<= u_max*z)
        @constraint(model, sum(z) <= s)
        @constraint(model, sum(u[j]^2 for j in 1:n_J) <= U_max^2)
        @objective(model, Max, sum(c_k[j] * u[j] for j in 1:n_J))
        optimize!(model)
        if termination_status(model) != MOI.OPTIMAL
            @warn "MIP subproblem not optimal: $(termination_status(model)), time used: $(solve_time(model))s"
            return zeros(n_J)
        end
        return value.(u)
    elseif method == "relaxed"
        @variable(model, 0 <= u[1:n_J]<=u_max)
        @variable(model, 0 <= z[1:n_J] <= 1)
        @constraint(model, u .<= u_max*z)
        @constraint(model, sum(z) <= s)
        @constraint(model, sum(u[j]^2 for j in 1:n_J) <= U_max^2)
        @objective(model, Max, sum(c_k[j] * u[j] for j in 1:n_J))
        optimize!(model)
        if termination_status(model) != MOI.OPTIMAL
            @warn "Relaxed subproblem not optimal: $(termination_status(model)), time used: $(solve_time(model))s"
            return zeros(n_J)
        end
        u_val = value.(u)
        return sparse_project(u_val, s)
    else
        error("Unknown method: $method. Use 'heuristic', 'mip', 'relaxed', or 'analytical'.")
    end
end

# --- 4. Solve Master Problem (RO-RJ with finite scenarios) ---
function solve_master_wireless(h, g, p_bar, gamma, sigma2, scenarios; optimizer=Mosek.Optimizer, total_time=0.0)
    m_UE, n_J, n_BS = size(g)
    model = Model(optimizer)
    set_silent(model)
    remaining_time = max(0.0, 1000.0 - total_time)
    set_optimizer_attribute(model, "MSK_DPAR_OPTIMIZER_MAX_TIME", remaining_time)
    @variable(model, 0 <= p[i=1:n_BS] <= p_bar[i])
    @objective(model, Min, sum(p))
    for k in 1:m_UE
        for u in scenarios
            interference_from_jammer = sum(u[j] * sum(p[i] * g[k, j, i] for i in 1:n_BS) for j in 1:n_J)
            sinr_term = sum(p[i] * h[k, i] for i in 1:n_BS) - gamma[k] * sigma2[k] - gamma[k] * interference_from_jammer
            #sinr_term = sum(p[i] * h[k, i] for i in 1:n_BS) - gamma * sigma2 - gamma * interference_from_jammer
            @constraint(model, sinr_term >= 0)
        end
    end
    optimize!(model)
    if termination_status(model) != MOI.OPTIMAL
        @warn "Master problem not optimal: $(termination_status(model)), time used: $(solve_time(model))s"
        return zeros(n_BS), Inf
    end
    return value.(p), objective_value(model)
end

# --- 5. Solve Nominal Problem (u = 0, i.e., no jamming) ---
function solve_nominal_wireless(h, p_bar, gamma, sigma2; optimizer=Mosek.Optimizer)
    m_UE, n_BS = size(h)
    model = Model(optimizer)
    set_silent(model)
    @variable(model, 0 <= p[i=1:n_BS] <= p_bar[i])
    @objective(model, Min, sum(p))
    for k in 1:m_UE
        @constraint(model, sum(p[i] * h[k, i] for i in 1:n_BS) - gamma[k] * sigma2[k] >= 0)
    end
    optimize!(model)
    if termination_status(model) != MOI.OPTIMAL
        @warn "Nominal wireless problem not optimal."
        return zeros(n_BS)
    end
    return value.(p)
end

# =============================================================================
# 6. Cutting Plane Algorithm for Wireless Optimization
# =============================================================================
function cutting_plane_wireless(
    h, g, p_bar, gamma, sigma2, s;
    method="heuristic",
    max_iter=5000,
    tol=1e-5,
    limit_time=1000.0,
    verbose=true,
    optimizer=Mosek.Optimizer,
    p_init=nothing,
    seed::Int=23,
    m_UE::Int=size(g, 1),
    n_J::Int=size(g, 2),
     n_BS::Int=size(g, 3),
    U_max::Float64=1000.0,      # ← added
    u_max::Float64=800.0        # ← added
)

    # Containers for scenario sets and τ history
    S = Vector{Vector{Float64}}()
    tau_history = Vector{Tuple{Int, Float64}}()

    # -------------------------------------------------------------------------
    # Initialization
    # -------------------------------------------------------------------------
    if isnothing(p_init)
        error("Initial power vector 'p_init' must be provided for wireless cutting-plane algorithm.")
    else
        p_current = p_init
        total_algorithm_time = 0.0
        if verbose
            println("(Initialized from provided solution (Seed $seed | m_UE=$m_UE, n_J=$n_J, n_BS=$n_BS | $method).)")
        end
    end

    τ_prev = Inf

    # -------------------------------------------------------------------------
    # Main Cutting-Plane Iteration Loop
    # -------------------------------------------------------------------------
    for ℓ in 1:max_iter
        if total_algorithm_time > limit_time
            if verbose
                println("⏰ Time limit ($limit_time s) exceeded at iteration $ℓ ($method | Seed $seed | m_UE=$m_UE, n_J=$n_J, n_BS=$n_BS)")
            end
            break
        end

        iter_time = 0.0
        new_scenarios = Vector{Vector{Float64}}()

        # ---------------------------------------------------------------------
        # Subproblem: Find worst-case jammer for each user
        # ---------------------------------------------------------------------
        t_sub = @elapsed begin
            for k in 1:m_UE
                c_k = [sum(p_current[i] * g[k, j, i] for i in 1:n_BS) for j in 1:n_J]
                u_k = worst_case_jammer(c_k, s; method=method, optimizer=optimizer, total_time=total_algorithm_time,
                             U_max=U_max,   # ← pass through
                             u_max=u_max)   # ← pass through)
                push!(new_scenarios, u_k)
            end
        end
        iter_time += t_sub

        # Add new worst-case scenarios
        append!(S, new_scenarios)

        # ---------------------------------------------------------------------
        # Master Problem: Update power allocation
        # ---------------------------------------------------------------------
        t_master = @elapsed p_opt, τ_current = solve_master_wireless(h, g, p_bar, gamma, sigma2, S; optimizer=optimizer, total_time=total_algorithm_time)
        iter_time += t_master
        total_algorithm_time += iter_time

        push!(tau_history, (ℓ, τ_current))
        p_current = p_opt

        # ---------------------------------------------------------------------
        # Convergence Check
        # ---------------------------------------------------------------------
        Δτ = ℓ > 1 ? abs(τ_current - τ_prev) : "N/A"

        if ℓ > 1 && isfinite(τ_current) && isfinite(τ_prev) && abs(τ_current - τ_prev) <= tol
            if verbose
                println("✅ Converged at iteration $ℓ: Δτ = $(abs(τ_current - τ_prev)) ($method | Seed $seed | m_UE=$m_UE)")
            end
            break
        end

        τ_prev = τ_current

        # ---------------------------------------------------------------------
        # Logging Progress
        # ---------------------------------------------------------------------
        if verbose && (ℓ == 1 || ℓ % 10 == 0)
            τ_str = isfinite(τ_current) ? round(τ_current, digits=6) : "Inf"
            delta_str = Δτ isa String ? Δτ : (isfinite(Δτ) ? round(Δτ, digits=6) : "Inf")
            println("Iteration $ℓ ($method | Seed $seed | m_UE=$m_UE): τ = $τ_str | Δτ = $delta_str | #Scenarios = $(length(S)) | Iter time = $(round(iter_time, digits=4))s")
        end
    end

    # -------------------------------------------------------------------------
    # Save results and summarize
    # -------------------------------------------------------------------------
    CSV.write("tau_wireless_$(method)_s$(s)_seed$(seed)_mUE$(m_UE)_nJ$(n_J)_nBS$(n_BS).csv",
              DataFrame(iteration=[t[1] for t in tau_history], tau=[t[2] for t in tau_history]))

    if verbose
        println("💾 Saved τ history: tau_wireless_$(method)_s$(s)_seed$(seed)_mUE$(m_UE)_nJ$(n_J)_nBS$(n_BS).csv")
        final_τ = isfinite(τ_prev) ? round(τ_prev, digits=6) : "Inf"
        #println("\n⏱️ TOTAL CUTTING-PLANE TIME ($method | Seed $seed | m_UE=$m_UE, n_J=$n_J, n_BS=$n_BS): $(round(total_algorithm_time, digits=4)) seconds")
        #println("📊 Final objective (τ): $final_τ")
    end

    return p_current, τ_prev, S, total_algorithm_time
end

println("✅ Cutting-plane wireless algorithm redefined successfully.")
########################################################################

# =============================================================================                1
# 7. RUN EXPERIMENT FOR WIRELESS OPTIMIZATION (MULTI-SEED, MULTI-METHOD)
# =============================================================================               done
using CSV, DataFrames, PrettyTables, Statistics

# --- Wireless problem configuration ---
WIRELESS_CONFIGS = [
   (n_BS=5, n_J=20, m_UE=50)
   ,(n_BS=10, n_J=50, m_UE=200)
  ,(n_BS=20, n_J=100, m_UE=300)
]

SEEDS = [1
, 2, 3, 4, 5
]  

methods = [
     "heuristic",
     "relaxed", 
     "mip"]
sparsities = [
    1,2,3,5
    ]

all_results = []

println("\n" * "^"^60)
println("🚀 STARTING CUTTING-PLANE ALGORITHM FOR WIRELESS PROBLEM (ALL METHODS, MULTI-SEED)")
# println("📡 Problem configurations: $(WIRELESS_CONFIGS)")
println("^"^60)

for (config_idx, config) in enumerate(WIRELESS_CONFIGS)
    n_BS, n_J, m_UE = config.n_BS, config.n_J, config.m_UE

    println("\n" * "="^60)
    println("📏 CONFIGURATION $config_idx: n_BS = $n_BS | n_J = $n_J | m_UE = $m_UE")
    println("="^60)

    for seed in SEEDS
        println("\n" * "#" * "="^58 * "#")
        println("### 🌱 Starting Wireless Experiment for SEED = $seed | n_BS = $n_BS | n_J = $n_J | m_UE = $m_UE ###")
        println("#" * "="^58 * "#")

        # ---------------------------------------------------------------------
        # Data Loading from .mat
        # ---------------------------------------------------------------------
        println("✅ Loading wireless data from .mat (seed=$seed)...")
        h, g, p_bar, gamma, sigma2, U_MAX, U_MAX_PER_JAMMER = load_wireless_data(n_BS, n_J, m_UE; seed=seed)
        # Save loaded data (optional)
        CSV.write("h_nBS$(n_BS)_nJ$(n_J)_mUE$(m_UE)_seed$(seed).csv", DataFrame(h, :auto))
       # println("💾 Saved h-matrix for seed=$seed")
        # (Optional: Save g, sigma2, etc., if needed)

        # ---------------------------------------------------------------------
        # Nominal Problem (No Jamming)
        # ---------------------------------------------------------------------
        #println("🧠 Computing nominal (no-jamming) solution (seed=$seed)...")
        nominal_time = @elapsed p_nominal = solve_nominal_wireless(h, p_bar, gamma, sigma2)
        nominal_obj = sum(p_nominal)
        println("✅ Nominal power: $(round(nominal_obj, digits=6)) | Time: $(round(nominal_time, digits=4))s")

        # ---------------------------------------------------------------------
        # Cutting-Plane Experiments
        # ---------------------------------------------------------------------
        for method in methods
            for s in sparsities
                println("\n" * "-"^50)
                println("▶️ Solving for sparsity s = $s | Method = $method | Seed = $seed")
                println("-"^50)

                total_elapsed = @elapsed begin
                    p_opt, τ_opt, scenarios, algo_time = cutting_plane_wireless(
                        h, g, p_bar, gamma, sigma2, s;
                        method=method,
                        max_iter=1000,
                        tol=1e-5,
                        limit_time=1000.0,
                        verbose=true,
                        optimizer=Mosek.Optimizer,
                        p_init=p_nominal,
                        #p_init =  p_bar,
                        seed=seed,
                        m_UE=m_UE,
                        n_J=n_J,
                        n_BS=n_BS,
                        U_max=U_MAX,              # ← new keyword arg
                        u_max=U_MAX_PER_JAMMER    # ← new keyword arg
                    )
                end

                # Record results
                push!(all_results, (
                    seed = seed,
                    n_BS = n_BS,
                    n_J = n_J,
                    m_UE = m_UE,
                    method = method,
                    sparsity = s,
                    total_power = τ_opt,
                    scenarios = length(scenarios),
                    algo_time = algo_time,
                    nominal_obj = nominal_obj
                ))

                # Save solution
                df_p = DataFrame(index=1:length(p_opt), p=p_opt)
                CSV.write("p_opt_$(method)_s$(s)_seed$(seed)_mUE$(m_UE)_nJ$(n_J)_nBS$(n_BS).csv", df_p)
                #println("💾 Saved: p_opt_$(method)_s$(s)_seed$(seed)_mUE$(m_UE)_nJ$(n_J)_nBS$(n_BS).csv")

                println("🏁 $method (Seed $seed): τ = $(round(τ_opt, digits=6)) | #Scenarios = $(length(scenarios)) | CP Time = $(round(algo_time, digits=4))s")
            end
        end
    end
end

# =============================================================================
# 8. RESULTS ANALYSIS (FIXED TABLE PRINTING)
# =============================================================================
println("\n📊 FINAL AGGREGATE REPORT (Across all Seeds and Configurations)")

if isempty(all_results)
    println("❌ No results collected.")
else
    df_final = DataFrame(all_results)

    # Correct renaming: :total_power → :LB
    rename!(df_final, :sparsity => :s, :total_power => :LB, :scenarios => Symbol("#Scenarios"), :algo_time => Symbol("Time (s)"))
    sort!(df_final, [:n_BS, :n_J, :m_UE, :seed, :s, :method])

    # --- COMPUTE AND ADD SGAP COLUMN ---
    gdf = groupby(df_final, [:n_BS, :n_J, :m_UE, :s, :seed])
    transform!(gdf, :LB => (LB -> maximum(filter(isfinite, LB))) => :LB_best, renamecols=false)
    transform!(gdf, [:LB_best, :LB] => ((LB_best, LB) -> (LB_best .- LB) ./ (abs.(LB) .+ 1e-4) .* 100) => Symbol("SGap (%)"), renamecols=false)
    select!(df_final, Not(:LB_best))

    # --- Save Detailed Results ---
    for (n_BS, n_J, m_UE) in [(c.n_BS, c.n_J, c.m_UE) for c in WIRELESS_CONFIGS]
        df_final_subset = filter(row -> row.n_BS == n_BS && row.n_J == n_J && row.m_UE == m_UE, df_final)
        CSV.write("wireless_final_results_nBS$(n_BS)_nJ$(n_J)_mUE$(m_UE).csv", df_final_subset)
        println("💾 Saved detailed report: wireless_final_results_nBS$(n_BS)_nJ$(n_J)_mUE$(m_UE).csv")
    end

    # --- Aggregate Summary Statistics ---
    for (n_BS, n_J, m_UE) in [(c.n_BS, c.n_J, c.m_UE) for c in WIRELESS_CONFIGS]
        df_subset = filter(row -> row.n_BS == n_BS && row.n_J == n_J && row.m_UE == m_UE, df_final)
        df_summary = combine(
            groupby(df_subset, [:s, :method]),
            :LB => (x -> round(mean(filter(isfinite, x)), digits=6)) => Symbol("Avg LB"),
            :LB => (x -> round(std(filter(isfinite, x)), digits=6)) => Symbol("Std LB"),
            Symbol("Time (s)") => (x -> round(mean(x), digits=2)) => Symbol("Avg Time (s)"),
            Symbol("Time (s)") => (x -> round(std(x), digits=2)) => Symbol("Std Time (s)"),
            Symbol("SGap (%)") => (x -> round(mean(x), digits=2)) => Symbol("Avg SGap (%)"),
            Symbol("SGap (%)") => (x -> round(std(x), digits=2)) => Symbol("Std SGap (%)")
        )
        sort!(df_summary, [:s, :method])

        # --- Display summary table using println ---
        println("\n" * "="^100)
        println("Summary Statistics (Averaged Across Seeds) — Wireless: n_BS=$n_BS, n_J=$n_J, m_UE=$m_UE")
        println("="^100)
        
        # Print header
        @printf("%-6s %-12s %-12s %-10s %-14s %-14s %-14s %-14s\n",
                "s", "Method", "Avg LB", "Std LB", "Avg Time (s)", "Std Time (s)", "Avg SGap (%)", "Std SGap (%)")
        println("-"^100)
        
        # Print rows
        for row in eachrow(df_summary)
            @printf("%-6d %-12s %-12.6f %-10.6f %-14.2f %-14.2f %-14.2f %-14.2f\n",
                    row[:s],
                    row[:method],
                    row[Symbol("Avg LB")],
                    row[Symbol("Std LB")],
                    row[Symbol("Avg Time (s)")],
                    row[Symbol("Std Time (s)")],
                    row[Symbol("Avg SGap (%)")],
                    row[Symbol("Std SGap (%)")]
            )
        end
        println("="^100)

        # Save summary report
        CSV.write("wireless_summary_nBS$(n_BS)_nJ$(n_J)_mUE$(m_UE).csv", df_summary)
        println("💾 Saved summary report: wireless_summary_nBS$(n_BS)_nJ$(n_J)_mUE$(m_UE).csv")
    end

    println("\n🎉 Wireless experiments completed for all seeds and configurations.")
end

# time limit (limit_time) is checked once per iteration at the beginning of the main loop. Specifically, the check occurs before any subproblems or the master problem are solved for that iteration.